services:
  db:
    image: postgres:latest
    container_name: washnow-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: washnow
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - washnow_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "washnow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: ./WashNowBackEnd
      dockerfile: Dockerfile
    container_name: washnow-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - washnow_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    ports:  # se precisar ajustar é só colocar 9091:9090, porta externa muda e interna continua igual
      - "9090:9090" # Porta padrão do Prometheus
    volumes:
      # temos de montar os volumes no path /etc/prometheus... padrão para que ele consiga encontrar os ficheiros
      - ./WashNowBackEnd/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - washnow_network

  grafana:
    image: grafana/grafana:11.5.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SenhaTeste123!
    ports:  # se precisar ajustar é só colocar 3001:3000, porta externa porta externa muda e interna continua igual
      - "3000:3000" # Porta padrão do Grafana
    volumes:
      # temos de montar os volumes no path /etc/grafana... padrão para que ele consiga encontrar os ficheiros
      - ./WashNowBackEnd/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./WashNowBackEnd/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - washnow_network
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    networks: 
      - washnow_network


networks:
  washnow_network:
    driver: bridge

volumes:
  db_data: