name: Deploy project

on:
  push:
    branches:
      - develop
      - MBA-55-finish-cd-pipeline

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verificar diretório atual e arquivos
        run: |
          pwd
          ls -la
          ls -la frontend
        
      - name: Start NGINX
        run: |
          sudo systemctl start nginx
          sudo systemctl reload nginx

      - name: Fazer build e subir com Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build --remove-orphans


     