name: Frontent

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a stable LTS version

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

      - name: Run Prettier
        run: npm run format-check
        working-directory: frontend