name: Continuous Integration
on: 
  push:
    branches:
      - main
      - dev

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu' # or 'temurin'
      - name: Run Tests
        working-directory: ./WashNowBackEnd
        run: mvn test -Dspring.profiles.active=test # Gera relatórios JUnit em `target/surefire-reports/`
      - name: Import results to Xray
        uses: mikepenz/xray-action@v3
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "target/surefire-reports/*.xml"  # Caminho padrão do Maven
          projectKey: "MBA"  # Substitua pela chave do seu projeto