name: Xray Test Report
on: [push]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test  # Gera relatórios JUnit em `target/surefire-reports/`
      - name: Import results to Xray
        uses: mikepenz/xray-action@v2
        with:
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "target/surefire-reports/*.xml"  # Caminho padrão do Maven
          projectKey: "MBA"  # Substitua pela chave do seu projeto